apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APP_NAME}
  labels:
    app: ${APP_NAME}
    stack: dotnet
    version: ${{ env.IMAGE_VERSION }}

spec:
  replicas: ${{ env.REPLICAS }}
  selector:
    matchLabels:
      app: ${APP_NAME}
  template:
    metadata:
      labels:
        app: ${APP_NAME}
    spec:
      containers:
      - name: ${APP_NAME}
        image: gperezivo/simple-api:${{ env.IMAGE_VERSION }}
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: MyVar
          value: ${IMAGE_VERSION}
        - name: MyVar2
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
---
apiVersion: v1
kind: Service
metadata:
  name: ${APP_NAME}
  labels:
    app: ${APP_NAME}
    version: ${{ env.IMAGE_VERSION }}
spec:
  selector:
    app: ${APP_NAME}
  ports:
  - port: 80
    targetPort: 80